const fs=require('fs'),path=require('path'),B='D:\\.openclaw\\workspace\\搅拌站出口项目\\yudaconcrete-site';

// Generate Spanish FAQ
var faq='<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">';
faq+='<title>FAQ | YUDA HUALONG - Preguntas Frecuentes</title>';
faq+='<meta name="description" content="Preguntas frecuentes sobre YUDA HUALONG plantas de hormigón.">';
faq+='<link rel="icon" type="image/svg+xml" href="../favicon.svg"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/style.css">';
faq+='<style>.nav-lang{position:relative}.lang-dropdown{display:none;position:absolute;top:100%;right:0;background:white;box-shadow:0 2px 12px rgba(0,0,0,0.15);border-radius:8px;min-width:160px;z-index:1000;padding:8px 0;list-style:none}.lang-dropdown li{padding:0}.lang-dropdown a{display:block;padding:8px 16px;color:var(--text);text-decoration:none;font-size:14px;white-space:nowrap}.lang-dropdown a:hover{background:var(--bg-light)}.nav-lang:hover .lang-dropdown{display:block}</style></head><body>';
faq+='<nav class="nav"><div class="nav-inner"><a href="/es/" class="nav-logo"><h1>YUDA HUALONG</h1><span>Plantas de Hormigón</span></a><ul class="nav-links"><li><a href="../">Inicio</a></li><li><a href="../products/concrete-batching-plant.html">Productos</a></li><li><a href="../products/hzs-concrete-batching-plant.html">Serie HZS</a></li><li><a href="../products/mobile-concrete-batching-plant.html">Plantas Móviles</a></li><li><a href="../about.html">Sobre Nosotros</a></li><li><a href="../countries/">Mercados Globales</a></li><li><a href="../contact.html" class="nav-cta">Solicitar Presupuesto</a></li><li class="nav-lang"><a href="javascript:void(0)" onclick="toggleLang()">[&#127760;] Español &#9660;</a><ul class="lang-dropdown"><li><a href="/">[EN] English</a></li><li><a href="/ru/">[RU] Русский</a></li><li><a href="/ar/">[AR] العربية</a></li><li><a href="/es/">[ES] Español</a></li><li><a href="/fr/">[FR] Français</a></li><li><a href="/pt/">[PT] Português</a></li></ul></li></ul></div></nav>';
faq+='<section class="page-header"><div class="container"><h1>Preguntas Frecuentes</h1><p>Respuestas a preguntas comunes sobre nuestras plantas de hormigón.</p></div></section>';
faq+='<section class="section"><div class="container" style="max-width:860px;margin:0 auto;">';
var qs=[
  ['¿Qué tipos de plantas de hormigón ofrecen?','Ofrecemos plantas fijas HZS (25-240 m³/h), plantas móviles y plantas sobre remolque. Cubrimos desde pequeñas obras hasta grandes proyectos comerciales.'],
  ['¿Cuál es su capacidad de producción?','Desde HZS25 (25 m³/h) hasta HZS240 (240 m³/h) y Doble HZS240 (480 m³/h). También ofrecemos plantas móviles con capacidades flexibles.'],
  ['¿Exportan a otros países?','Sí, exportamos a Asia Central, África, Medio Oriente, América del Sur y Europa. Tenemos experiencia en más de 7 países.'],
  ['¿Qué certificaciones tienen?','CE, ISO 9001, patentes de utilidad, Alibaba Gold Supplier. Todas las certificaciones verificables.'],
  ['¿Cuál es el tiempo de entrega?','Generalmente 15-30 días según el modelo y la cantidad. Para modelos estándar el plazo es más corto.'],
  ['¿Ofrecen instalación en el sitio?','Sí, proporcionamos ingenieros para instalación y capacitación in situ. También ofrecemos soporte técnico remoto.'],
  ['¿Cuál es el período de garantía?','12 meses a partir de la puesta en marcha. Cubrimos defectos de fabricación y ofrecemos soporte postventa.'],
  ['¿Puedo visitar su fábrica?','¡Por supuesto! Bienvenido a Zhengzhou. Proporcionamos transporte al aeropuerto y asistencia de alojamiento.']
];
qs.forEach(function(q,i){faq+='<div style="margin-bottom:20px;padding:20px;background:var(--bg-light);border-radius:var(--radius);"><h3 style="margin-bottom:8px;">'+(i+1)+'. '+q[0]+'</h3><p style="color:var(--text-gray);">'+q[1]+'</p></div>';});
faq+='</div></section>';
faq+='<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><h3>YUDA HUALONG</h3><p>Fabricante profesional de plantas de hormigón. Directo de fábrica desde Zhengzhou, China.</p><p style="margin-top:12px;">Tel: +86 18638788818</p></div>';
faq+='<div><h4>Productos</h4><ul><li><a href="../products/hzs-concrete-batching-plant.html">Serie HZS</a></li><li><a href="../products/mobile-concrete-batching-plant.html">Plantas Móviles</a></li><li><a href="../products/concrete-mixer.html">Mezcladora</a></li><li><a href="../products/concrete-batching-plant.html">Todos los Productos</a></li></ul></div>';
faq+='<div><h4>Empresa</h4><ul><li><a href="../about.html">Sobre YUDA</a></li><li><a href="../company/factory.html">Fábrica</a></li><li><a href="../company/certificates.html">Certificaciones</a></li><li><a href="../company/customer-visits.html">Visitas de Clientes</a></li><li><a href="../countries/">Mercados Globales</a></li></ul></div>';
faq+='<div><h4>Soporte</h4><ul><li><a href="../contact.html">Contacto</a></li><li><a href="../faq.html">FAQ</a></li></ul></div></div><div class="footer-bottom">© 2026 YUDA HUALONG. Todos los derechos reservados. | Zhengzhou, Henan, China</div></div></footer>';
faq+='<script>function toggleLang(){document.querySelector(\'.lang-dropdown\').classList.toggle(\'show\');}document.addEventListener(\'click\',function(e){if(!e.target.closest(\'.nav-lang\'))document.querySelector(\'.lang-dropdown\')?.classList.remove(\'show\');});</script></body></html>';
fs.writeFileSync(path.join(B,'es/faq.html'),faq,'utf8');
console.log('OK: es/faq.html');

// Generate Spanish projects
var proj='<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">';
proj+='<title>Proyectos | YUDA HUALONG - Casos de Éxito</title>';
proj+='<link rel="icon" type="image/svg+xml" href="../favicon.svg"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/style.css">';
proj+='<style>.nav-lang{position:relative}.lang-dropdown{display:none;position:absolute;top:100%;right:0;background:white;box-shadow:0 2px 12px rgba(0,0,0,0.15);border-radius:8px;min-width:160px;z-index:1000;padding:8px 0;list-style:none}.lang-dropdown li{padding:0}.lang-dropdown a{display:block;padding:8px 16px;color:var(--text);text-decoration:none;font-size:14px;white-space:nowrap}.lang-dropdown a:hover{background:var(--bg-light)}.nav-lang:hover .lang-dropdown{display:block}</style></head><body>';
proj+='<nav class="nav"><div class="nav-inner"><a href="/es/" class="nav-logo"><h1>YUDA HUALONG</h1><span>Plantas de Hormigón</span></a><ul class="nav-links"><li><a href="../">Inicio</a></li><li><a href="../products/concrete-batching-plant.html">Productos</a></li><li><a href="../products/hzs-concrete-batching-plant.html">Serie HZS</a></li><li><a href="../products/mobile-concrete-batching-plant.html">Plantas Móviles</a></li><li><a href="../about.html">Sobre Nosotros</a></li><li><a href="../countries/">Mercados Globales</a></li><li><a href="../contact.html" class="nav-cta">Solicitar Presupuesto</a></li><li class="nav-lang"><a href="javascript:void(0)" onclick="toggleLang()">[&#127760;] Español &#9660;</a><ul class="lang-dropdown"><li><a href="/">[EN] English</a></li><li><a href="/ru/">[RU] Русский</a></li><li><a href="/ar/">[AR] العربية</a></li><li><a href="/es/">[ES] Español</a></li><li><a href="/fr/">[FR] Français</a></li><li><a href="/pt/">[PT] Português</a></li></ul></li></ul></div></nav>';
proj+='<section class="page-header"><div class="container"><h1>Proyectos</h1><p>Casos de éxito de YUDA HUALONG en todo el mundo</p></div></section>';
proj+='<section class="section"><div class="container" style="max-width:900px;margin:0 auto;">';
proj+='<p style="color:var(--text-gray);margin-bottom:30px;">YUDA HUALONG ha suministrado plantas de hormigón para numerosos proyectos alrededor del mundo. Aquí presentamos algunos de nuestros casos de éxito.</p>';
proj+='<div class="why-card" style="margin-bottom:20px;text-align:left;"><h3>Proyecto Rusia - Planta HZS120</h3><p style="color:var(--text-gray);">Instalación de una planta de hormigón HZS120 en Rusia para un importante proyecto de infraestructura. Capacidad de producción de 120 m³/h, con mezcladora JS2000 de doble eje forzado.</p></div>';
proj+='<div class="why-card" style="margin-bottom:20px;text-align:left;"><h3>Proyecto Kazajistán - Planta HZS90</h3><p style="color:var(--text-gray);">Planta HZS90 instalada en Kazajistán para un proyecto de construcción de carreteras. Equipo confiable para condiciones climáticas extremas.</p></div>';
proj+='<div class="why-card" style="margin-bottom:20px;text-align:left;"><h3>Proyecto África - Planta Móvil</h3><p style="color:var(--text-gray);">Planta de hormigón móvil suministrada para un proyecto de construcción en África. Rápida instalación y fácil reubicación.</p></div>';
proj+='<div class="cta-section" style="border-radius:var(--radius);padding:40px;margin-top:30px;"><h3 style="color:white;margin-bottom:12px;">¿Tiene un proyecto?</h3><p style="color:rgba(255,255,255,0.7);margin-bottom:24px;">Contáctenos para discutir sus necesidades de planta de hormigón.</p><a href="../contact.html" class="btn btn-primary">Contáctenos</a></div>';
proj+='</div></section>';
proj+='<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><h3>YUDA HUALONG</h3><p>Fabricante profesional de plantas de hormigón. Directo de fábrica desde Zhengzhou, China.</p><p style="margin-top:12px;">Tel: +86 18638788818</p></div>';
proj+='<div><h4>Productos</h4><ul><li><a href="../products/hzs-concrete-batching-plant.html">Serie HZS</a></li><li><a href="../products/mobile-concrete-batching-plant.html">Plantas Móviles</a></li><li><a href="../products/concrete-mixer.html">Mezcladora</a></li><li><a href="../products/concrete-batching-plant.html">Todos los Productos</a></li></ul></div>';
proj+='<div><h4>Empresa</h4><ul><li><a href="../about.html">Sobre YUDA</a></li><li><a href="../company/factory.html">Fábrica</a></li><li><a href="../company/certificates.html">Certificaciones</a></li><li><a href="../company/customer-visits.html">Visitas de Clientes</a></li><li><a href="../countries/">Mercados Globales</a></li></ul></div>';
proj+='<div><h4>Soporte</h4><ul><li><a href="../contact.html">Contacto</a></li><li><a href="../faq.html">FAQ</a></li></ul></div></div><div class="footer-bottom">© 2026 YUDA HUALONG. Todos los derechos reservados. | Zhengzhou, Henan, China</div></div></footer>';
proj+='<script>function toggleLang(){document.querySelector(\'.lang-dropdown\').classList.toggle(\'show\');}document.addEventListener(\'click\',function(e){if(!e.target.closest(\'.nav-lang\'))document.querySelector(\'.lang-dropdown\')?.classList.remove(\'show\');});</script></body></html>';
fs.writeFileSync(path.join(B,'es/projects/index.html'),proj,'utf8');
console.log('OK: es/projects/index.html');
